image: gitpod/workspace-full

tasks:
  - init: yarn install
    command: yarn start

ports:
  - port: 8000
    onOpen: open-preview

  - port: 9229
    onOpen: ignore

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
